<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NbPersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbPersonneRepository extends EntityRepository
{
}
